name: aprende_mas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  dio: ^5.6.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.11
  formz: ^0.7.0
  go_router: ^14.2.7
  google_generative_ai: ^0.4.6
  intl: ^0.19.0
  syncfusion_flutter_calendar: ^27.1.51
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/
