name: aprende_mas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  dio: ^5.6.0
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.5.1
  fluttertoast: ^8.2.8
  font_awesome_flutter: ^10.7.0
  formz: ^0.7.0
  go_router: ^14.2.7
  google_generative_ai: ^0.4.6
  syncfusion_flutter_calendar: ^27.1.51
  google_nav_bar: ^5.0.6
  google_sign_in: ^6.2.1
  shared_preferences: ^2.3.2
  syncfusion_flutter_calendar: ^27.1.51

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/logo.png
